import React, {Component} from 'react'
import {connect} from 'react-redux'
import {withRouter, Route, Switch} from 'react-router-dom'
import PropTypes from 'prop-types'
import {Login, Signup, UserHome} from './components'
import {me} from './store'
import SingleCoffeePage from './components/SingleCoffeePage'
import AllCoffees from './components/AllCoffees'
import {HomePage} from './components/Homepage'
import Abou